stages:
  - Build
  - Deploy



Build oEMS Edge:
  stage: Build
  script:
    - apt update
    - apt install -y openjdk-8-jdk git
    - ./gradlew build
    - ./gradlew buildComponents
    - ./gradlew buildEdge


  except:
    - /^[a-z]*\/release\/[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}-[0-9]{1,2}$/
  artifacts:
    paths:
      - build/
    expire_in: 1 day



Deploy:
  stage: Deploy
  script:
    - echo Uploading software to repo
    - apt update
    - apt install -y openjdk-8-jdk git
    - apt install curl
    - ./gradlew build
    - ./gradlew buildEdge
    - ./gradlew buildEdgeDeb
    - ./release.sh upload
  only:
    - /^[a-z]*\/release\/[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}-[0-9]{1,2}$/
  artifacts:
    paths:
      - build/
    expire_in: 1 day

