= Wolf Chp

This module reads the most important variables available via Modbus from a Wolf chp and maps them to OpenEMS
channels. The module is written to be used with the Heater interface EnableSignal methods and ExceptionalState.
When setEnableSignal() from the Heater interface is set to true with no other parameters like electric power specified,
the chp will turn on with default settings. The default settings are configurable in the config.

The chp can be controlled with setElectricPowerSetpoint() (set power in kW). Set point methods from the Heater
interface (setTemperatureSetpoint(), setHeatingPowerSetpoint() and setHeatingPowerPercentSetpoint()) are not supported.

This chp has two other control methods besides setElectricPowerSetpoint(), which are setFeedInSetpoint() and
setReserveSetpoint(). The chp changes to the corresponding mode when a set point method is used.
If different types of set point methods are used in the same cycle, the hierarchy is: electric power > feed-in > reserve.
The lower hierarchy setting will be ignored.

If the chp is activated by ExceptionalState, it will convert the ExceptionalStateValue into a setElectricPowerSetpoint() value.

https://github.com/OpenEMS/openems/tree/develop/io.openems.edge.heater.chp.wolf[Source Code icon:github[]]

// ToDo: Granularity of electric power setpoint is very coarse. The Wolf GTK 4 has 4 kW electric
//  power. Modbus power set point is an int with unit kW. Usually a chp can only go as low as 50%
//  of maximum power. That means the GTK 4 has only 3 possible set points: 2 kW, 3 kW and 4 kW.
//  Check if that is really the case or if manual is wrong about power set point unit.