package io.openems.edge.heater.chp.dachs.api;

import io.openems.common.channel.AccessMode;
import io.openems.common.channel.Unit;
import io.openems.common.types.OpenemsType;
import io.openems.edge.common.channel.BooleanReadChannel;
import io.openems.edge.common.channel.Doc;
import io.openems.edge.common.channel.DoubleReadChannel;
import io.openems.edge.common.channel.IntegerReadChannel;
import io.openems.edge.common.channel.StringReadChannel;
import io.openems.edge.common.channel.value.Value;
import io.openems.edge.heater.api.Chp;

/**
 * Channels for the Dachs CHP.
 */
public interface DachsGltInterface extends Chp {

    public enum ChannelId implements io.openems.edge.common.channel.ChannelId {

        /**
         * Dachs request of run.
         * (Dachs-Lauf-Anforderung, Hka_Bd.UHka_Anf.usAnforderung)
         * <ul>
         * <li>Type: string
         * </ul>
         */
        REQUEST_OF_RUN_BITS(Doc.of(OpenemsType.STRING).accessMode(AccessMode.READ_ONLY)),

        /**
         * Requested modules setting. Only available (!=0) if Dachs has more than one module. 
         * (Anzahl der angeforderten Module, Hka_Bd.Anforderung.ModulAnzahl)
         * <ul>
         * <li>Type: integer
         * </ul>
         */
        NUMBER_OF_MODULES(Doc.of(OpenemsType.INTEGER).unit(Unit.NONE).accessMode(AccessMode.READ_ONLY)),

        /**
         * Dachs run enable bits.
         * (Dachs-Lauf-Freigabe, Hka_Bd.UHka_Frei.usFreigabe)
         * <ul>
         * <li>Type: string
         * </ul>
         */
        RUN_ENABLE_BITS(Doc.of(OpenemsType.STRING).accessMode(AccessMode.READ_ONLY)),

        /**
         * Enable electricity bits.
         * (Strom-Freigabe, Freigabe Stromfuehrung, Hka_Bd.UStromF_Frei.bFreigabe)
         * <ul>
         * <li>Type: string
         * </ul>
         */
        ENABLE_ELECTRICITY_BITS(Doc.of(OpenemsType.STRING).accessMode(AccessMode.READ_ONLY)),

        /**
         * Electricity request flag. Result of the electricity request bits.
         * (Anforderungen Strom, Hka_Bd.UHka_Anf.Anforderung.fStrom)
         * <ul>
         * <li>Type: boolean
         * </ul>
         */
        ELECTRICITY_REQUEST_FLAG(Doc.of(OpenemsType.BOOLEAN).accessMode(AccessMode.READ_ONLY)),

        /**
         * Electricity request bits.
         * (Strom-Anforderung, Anforderungen Stromfuehrung, Hka_Bd.Anforderung.UStromF_Anf.bFlagSF)
         * <ul>
         * <li>Type: string
         * </ul>
         */
        ELECTRICITY_REQUEST_BITS(Doc.of(OpenemsType.STRING).accessMode(AccessMode.READ_ONLY)),

        /**
         * Electrical work generated by the chp since the last restart. 
         * (Hka_Bd.ulArbeitElektr)
         * <ul>
         * <li>Type: double
         * <li>Unit: kilowatt hours
         * </ul>
         */
        ELECTRICAL_WORK(Doc.of(OpenemsType.DOUBLE).unit(Unit.KILOWATT_HOURS).accessMode(AccessMode.READ_ONLY)),

        /**
         * Thermal work generated by the chp since the last restart. 
         * (Hka_Bd.ulArbeitThermHka)
         * <ul>
         * <li>Type: double
         * <li>Unit: kilowatt hours
         * </ul>
         */
        THERMAL_WORK(Doc.of(OpenemsType.DOUBLE).unit(Unit.KILOWATT_HOURS).accessMode(AccessMode.READ_ONLY)),

        /**
         * Thermal work generated by the condenser since the last restart. 
         * (Hka_Bd.ulArbeitThermKon)
         * <ul>
         * <li>Type: double
         * <li>Unit: kilowatt hours
         * </ul>
         */
        THERMAL_WORK_COND(Doc.of(OpenemsType.DOUBLE).unit(Unit.KILOWATT_HOURS).accessMode(AccessMode.READ_ONLY)),

        /**
         * Time since last restart. 
         * (Hka_Bd.ulBetriebssekunden) (<- unit is hours, even if this says otherwise)
         * <ul>
         * <li>Type: double
         * <li>Unit: hours
         * </ul>
         */
        RUNTIME(Doc.of(OpenemsType.DOUBLE).unit(Unit.HOUR).accessMode(AccessMode.READ_ONLY)),

        /**
         * Rotations per minute of the chp engine. 
         * (Hka_Mw1.usDrehzahl)
         * <ul>
         * <li>Type: integer
         * <li>Unit: rotations per minute
         * </ul>
         */
        RPM(Doc.of(OpenemsType.INTEGER).unit(Unit.ROTATION_PER_MINUTE).accessMode(AccessMode.READ_ONLY)),

        /**
         * Engine starts since last restart of the chp. 
         * (Hka_Bd.ulAnzahlStarts)
         * <ul>
         * <li>Type: integer
         * </ul>
         */
        ENGINE_STARTS(Doc.of(OpenemsType.INTEGER).unit(Unit.NONE).accessMode(AccessMode.READ_ONLY)),

        /**
         * Serial number as a string. 
         * (Hka_Bd_Stat.uchSeriennummer)
         * <ul>
         * <li>Type: string
         * </ul>
         */
        SERIAL_NUMBER(Doc.of(OpenemsType.STRING).accessMode(AccessMode.READ_ONLY)),

        /**
         * Parts number as a string. 
         * (Hka_Bd_Stat.uchTeilenummer)
         * <ul>
         * <li>Type: string
         * </ul>
         */
        PARTS_NUMBER(Doc.of(OpenemsType.STRING).accessMode(AccessMode.READ_ONLY)),

        /**
         * Maintenance needed flag. If true will trigger a text in WARNING_MESSAGE.
         * (Wartung_Cache.fStehtAn)
         * <ul>
         * <li>Type: boolean
         * </ul>
         */
        MAINTENANCE(Doc.of(OpenemsType.BOOLEAN).accessMode(AccessMode.READ_ONLY)),

		// Warning message, (Hka_Bd.bWarnung) - included in Heater

		// Error message, (Hka_Bd.bStoerung) - included in Heater
		;

        private final Doc doc;

        ChannelId(Doc doc) {
            this.doc = doc;
        }

        public Doc doc() {
            return this.doc;
        }

    }


    /**
     * Gets the Channel for {@link ChannelId#REQUEST_OF_RUN_BITS}.
     *
     * @return the Channel
     */
    default StringReadChannel getRequestOfRunBitsChannel() {
        return this.channel(ChannelId.REQUEST_OF_RUN_BITS);
    }
    
    /**
	 * Get the Dachs request of run bits as a string.
	 * (Dachs-Lauf-Anforderung, Hka_Bd.UHka_Anf.usAnforderung)
	 * See {@link ChannelId#REQUEST_OF_RUN_BITS}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<String> getRequestOfRunBits() {
		return this.getRequestOfRunBitsChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#REQUEST_OF_RUN_BITS}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setRequestOfRunBits(String value) {
		this.getRequestOfRunBitsChannel().setNextValue(value);
	}

    /**
     * Gets the Channel for {@link ChannelId#NUMBER_OF_MODULES}.
     *
     * @return the Channel
     */
    default IntegerReadChannel getNumberOfModulesChannel() {
        return this.channel(ChannelId.NUMBER_OF_MODULES);
    }
    
    /**
     * Number of requested modules. Only available (!=0) if Dachs has more than one module.
     * (Anzahl der angeforderten Module, Hka_Bd.Anforderung.ModulAnzahl)
	 * See {@link ChannelId#NUMBER_OF_MODULES}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<Integer> getNumberOfModules() {
		return this.getNumberOfModulesChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#NUMBER_OF_MODULES}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setNumberOfModules(Integer value) {
		this.getNumberOfModulesChannel().setNextValue(value);
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#NUMBER_OF_MODULES}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setNumberOfModules(int value) {
		this.getNumberOfModulesChannel().setNextValue(value);
	}

    /**
     * Gets the Channel for {@link ChannelId#RUN_ENABLE_BITS}.
     *
     * @return the Channel
     */
    default StringReadChannel getRunEnableBitsChannel() {
        return this.channel(ChannelId.RUN_ENABLE_BITS);
    }
    
    /**
	 * Get the Dachs run enable bits as a string.
	 * (Dachs-Lauf-Freigabe, Hka_Bd.UHka_Frei.usFreigabe)
	 * See {@link ChannelId#RUN_ENABLE_BITS}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<String> getRunEnableBits() {
		return this.getRunEnableBitsChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#RUN_ENABLE_BITS}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setRunEnableBits(String value) {
		this.getRequestOfRunBitsChannel().setNextValue(value);
	}

    /**
     * Gets the Channel for {@link ChannelId#ENABLE_ELECTRICITY_BITS}.
     *
     * @return the Channel
     */
    default StringReadChannel getEnableElectricityBitsChannel() {
        return this.channel(ChannelId.ENABLE_ELECTRICITY_BITS);
    }
    
    /**
	 * Get the enable electricity bits as a string.
	 * (Strom-Freigabe, Freigabe Stromfuehrung, Hka_Bd.UStromF_Frei.bFreigabe)
	 * See {@link ChannelId#ENABLE_ELECTRICITY_BITS}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<String> getEnableElectricityBits() {
		return this.getEnableElectricityBitsChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#ENABLE_ELECTRICITY_BITS}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setEnableElectricityBits(String value) {
		this.getEnableElectricityBitsChannel().setNextValue(value);
	}

	/**
     * Gets the Channel for {@link ChannelId#ELECTRICITY_REQUEST_FLAG}.
     *
     * @return the Channel
     */
	default BooleanReadChannel getElectricityRequestFlagChannel() {
        return this.channel(ChannelId.ELECTRICITY_REQUEST_FLAG);
    }
    
    /**
	 * Get the electricity request flag, the result of the electricity request bits.
	 * (Anforderungen Strom, Hka_Bd.UHka_Anf.Anforderung.fStrom)
	 * See {@link ChannelId#ELECTRICITY_REQUEST_FLAG}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<Boolean> getElectricityRequestFlag() {
		return this.getElectricityRequestFlagChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#ELECTRICITY_REQUEST_FLAG}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setElectricityRequestFlag(Boolean value) {
		this.getElectricityRequestFlagChannel().setNextValue(value);
	}

	/**
     * Gets the Channel for {@link ChannelId#ELECTRICITY_REQUEST_BITS}.
     *
     * @return the Channel
     */
	default StringReadChannel getElectricityRequestBitsChannel() {
        return this.channel(ChannelId.ELECTRICITY_REQUEST_BITS);
    }
    
    /**
	 * Get the electricity request bits as a string.
	 * (Strom-Anforderung, Anforderungen Stromfuehrung, Hka_Bd.Anforderung.UStromF_Anf.bFlagSF)
	 * See {@link ChannelId#ELECTRICITY_REQUEST_BITS}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<String> getElectricityRequestBits() {
		return this.getElectricityRequestBitsChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#ELECTRICITY_REQUEST_BITS}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setElectricityRequestBits(String value) {
		this.getElectricityRequestBitsChannel().setNextValue(value);
	}

	/**
     * Gets the Channel for {@link ChannelId#ELECTRICAL_WORK}.
     *
     * @return the Channel
     */
	default DoubleReadChannel getElectricalWorkChannel() {
        return this.channel(ChannelId.ELECTRICAL_WORK);
    }
    
    /**
     * Electrical work generated by the chp since the last restart, in kilowatt hours.
	 * (Hka_Bd.ulArbeitElektr)
	 * See {@link ChannelId#ELECTRICAL_WORK}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<Double> getElectricalWork() {
		return this.getElectricalWorkChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#ELECTRICAL_WORK}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setElectricalWork(Double value) {
		this.getElectricalWorkChannel().setNextValue(value);
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#ELECTRICAL_WORK}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setElectricalWork(double value) {
		this.getElectricalWorkChannel().setNextValue(value);
	}

	/**
     * Gets the Channel for {@link ChannelId#THERMAL_WORK}.
     *
     * @return the Channel
     */
	default DoubleReadChannel getThermalWorkChannel() {
        return this.channel(ChannelId.THERMAL_WORK);
    }
    
    /**
     * Thermal work generated by the chp since the last restart, in kilowatt hours.
	 * (Hka_Bd.ulArbeitThermHka)
	 * See {@link ChannelId#THERMAL_WORK}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<Double> getThermalWork() {
		return this.getThermalWorkChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#THERMAL_WORK}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setThermalWork(Double value) {
		this.getThermalWorkChannel().setNextValue(value);
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#THERMAL_WORK}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setThermalWork(double value) {
		this.getThermalWorkChannel().setNextValue(value);
	}
	
	/**
     * Gets the Channel for {@link ChannelId#THERMAL_WORK_COND}.
     *
     * @return the Channel
     */
	default DoubleReadChannel getThermalWorkCondChannel() {
        return this.channel(ChannelId.THERMAL_WORK_COND);
    }
    
    /**
     * Thermal work generated by the condenser since the last restart, in kilowatt hours.
	 * (Hka_Bd.ulArbeitThermKon)
	 * See {@link ChannelId#THERMAL_WORK_COND}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<Double> getThermalWorkCond() {
		return this.getThermalWorkCondChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#THERMAL_WORK_COND}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setThermalWorkCond(Double value) {
		this.getThermalWorkCondChannel().setNextValue(value);
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#THERMAL_WORK_COND}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setThermalWorkCond(double value) {
		this.getThermalWorkCondChannel().setNextValue(value);
	}
	
	/**
     * Gets the Channel for {@link ChannelId#RUNTIME}.
     *
     * @return the Channel
     */
	default DoubleReadChannel getRuntimeSinceRestartChannel() {
        return this.channel(ChannelId.RUNTIME);
    }
    
    /**
     * Time since last restart in hours.
	 * (Hka_Bd.ulBetriebssekunden) (<- unit is hours, even if this says otherwise)
	 * See {@link ChannelId#RUNTIME}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<Double> getRuntimeSinceRestart() {
		return this.getRuntimeSinceRestartChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#RUNTIME}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setRuntimeSinceRestart(Double value) {
		this.getRuntimeSinceRestartChannel().setNextValue(value);
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#RUNTIME}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setRuntimeSinceRestart(double value) {
		this.getRuntimeSinceRestartChannel().setNextValue(value);
	}
	
	/**
     * Gets the Channel for {@link ChannelId#RPM}.
     *
     * @return the Channel
     */
	default IntegerReadChannel getRpmChannel() {
        return this.channel(ChannelId.RPM);
    }
    
    /**
     * Rotations per minute of the chp engine.
	 * (Hka_Mw1.usDrehzahl)
	 * See {@link ChannelId#RPM}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<Integer> getRpm() {
		return this.getRpmChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#RPM}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setRpm(Integer value) {
		this.getRpmChannel().setNextValue(value);
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#RPM}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setRpm(int value) {
		this.getRpmChannel().setNextValue(value);
	}
	
	/**
     * Gets the Channel for {@link ChannelId#ENGINE_STARTS}.
     *
     * @return the Channel
     */
	default IntegerReadChannel getEngineStartsChannel() {
        return this.channel(ChannelId.ENGINE_STARTS);
    }
    
    /**
     * Engine starts since last restart of the chp.
	 * (Hka_Bd.ulAnzahlStarts)
	 * See {@link ChannelId#ENGINE_STARTS}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<Integer> getEngineStarts() {
		return this.getEngineStartsChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#ENGINE_STARTS}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setEngineStarts(Integer value) {
		this.getEngineStartsChannel().setNextValue(value);
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#ENGINE_STARTS}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setEngineStarts(int value) {
		this.getEngineStartsChannel().setNextValue(value);
	}
	
	/**
     * Gets the Channel for {@link ChannelId#SERIAL_NUMBER}.
     *
     * @return the Channel
     */
	default StringReadChannel getSerialNumberChannel() {
        return this.channel(ChannelId.SERIAL_NUMBER);
    }
    
    /**
	 * Serial number.
	 * (Hka_Bd_Stat.uchSeriennummer)
	 * See {@link ChannelId#SERIAL_NUMBER}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<String> getSerialNumber() {
		return this.getSerialNumberChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#SERIAL_NUMBER}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setSerialNumber(String value) {
		this.getSerialNumberChannel().setNextValue(value);
	}
	
	/**
     * Gets the Channel for {@link ChannelId#PARTS_NUMBER}.
     *
     * @return the Channel
     */
	default StringReadChannel getPartsNumberChannel() {
        return this.channel(ChannelId.PARTS_NUMBER);
    }
    
    /**
	 * Parts number.
	 * (Hka_Bd_Stat.uchTeilenummer)
	 * See {@link ChannelId#PARTS_NUMBER}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<String> getPartsNumber() {
		return this.getPartsNumberChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#PARTS_NUMBER}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setPartsNumber(String value) {
		this.getPartsNumberChannel().setNextValue(value);
	}

	/**
     * Gets the Channel for {@link ChannelId#MAINTENANCE}.
     *
     * @return the Channel
     */
	default BooleanReadChannel getMaintenanceFlagChannel() {
        return this.channel(ChannelId.MAINTENANCE);
    }
    
    /**
	 * Flag signaling that a maintenance is needed soon. If true will trigger a text in WARNING_MESSAGE.
	 * (Wartung_Cache.fStehtAn)
	 * See {@link ChannelId#MAINTENANCE}.
	 *
	 * @return the Channel {@link Value}
	 */
    default Value<Boolean> getMaintenanceFlag() {
		return this.getMaintenanceFlagChannel().value();
	}
	
	/**
	 * Internal method to set the 'nextValue' on {@link ChannelId#MAINTENANCE}
	 * Channel.
	 *
	 * @param value the next value
	 */
	default void _setMaintenanceFlag(Boolean value) {
		this.getMaintenanceFlagChannel().setNextValue(value);
	}
}
